const AuthActionTypes = {
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    VERIFY_ACCOUNT: "VERIFY_ACCOUNT",
    VERIFY_ACCOUNT_SUCCESS: "VERIFY_ACCOUNT_SUCCESS",
    VERIFY_ACCOUNT_FAILURE: "VERIFY_ACCOUNT_FAILURE",
    LOGOUT: "LOGOUT",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  };
  
  export default AuthActionTypes;
  